Allow optional block number parameter
nomiclabs/buidler pull request #778
Opened 2020-09-07 19:03 UTC by nebojsa94

This PR allows optional block number parameter in RPC methods eth_call, eth_estimateGas, eth_getBalance, eth_getTransactionsCount, eth_getStorageAt and eth_getCode.

2020-09-10 12:47 UTC, alcuadrado commented
Hey @nebojsa94,

Thanks for submitting this PR. As Andrej probably told you, we'd like to release this soon, so you can start testing your integration with it.

Can I request two simple changes? I'm worried that how this is built rn will make the integration with #768 harder.

These are:

1. Instead of getting the `storageRoot` in the eth module, pass the block number to the node and manage that there. The reason for this is that when forking mainnet you have to forward some requests to a node through JSON-RPC and there's no direct way to do that using the storage root as a param.

2. Can we introduce some kind of helper into the node so the set/reset storage root isn't repeated? Something like this should do:

```ts
private async _runOnBlockContext<T>(blockNumber:BN, action:() => Promise<T>):Promise<T> {
     // get storage root by block number
     // set the storage root
    try {
       return await action(); // I think the await here is crucial
    } finally {
         // reset the storage root
    }
}
```

2020-09-10 12:56 UTC, fvictorio commented
Yep, that makes sense!

2020-09-12 12:37 UTC, alcuadrado commented on packages/buidler-core/test/internal/buidler-evm/provider/modules/eth.ts
> +          assert.isTrue(new BN(toBuffer(result)).gt(new BN(toBuffer(result2))));
clever!

2020-09-12 12:46 UTC, alcuadrado requested changes
Sorry, I didn't notice this before, but it's a bit confusing how block numbers are handled when using "pending", especially in `runCall`.

I think we can use `null` to represent "pending", and BNs everywhere else.

2020-09-12 12:46 UTC, alcuadrado commented on packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
> +  ): Promise<BN> {
Make this `BN | null`.

2020-09-12 12:46 UTC, alcuadrado commented on packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
> +      blockTag === "pending"
If `"pending"`, return `null`.

2020-09-12 12:46 UTC, alcuadrado commented on packages/buidler-core/src/internal/buidler-evm/provider/node.ts
> +    blockNumber: BN | null,
`null` here would mean `pending`, which for now is the latest block, so no modification is needed.

2020-09-12 12:46 UTC, alcuadrado commented on packages/buidler-core/src/internal/buidler-evm/provider/node.ts
> +    runOnNewBlock: boolean,
`runOnNewBlock` can go away

2020-09-12 12:46 UTC, alcuadrado commented on packages/buidler-core/src/internal/buidler-evm/provider/node.ts
> +      this._runTxAndRevertMutations(tx, runOnNewBlock)
Here `runOnNewBlock` should be `blockNumber === null`.

2020-09-12 13:06 UTC, alcuadrado commented
I have push access to your repo, so I fixed those things. Thanks for doing the changes I asked for @nebojsa94

2020-09-12 13:31 UTC, merged